### ISSUE TITLE
Add templates

### ISSUE THREAD

**Issue by egorsmkv** [bzzzzzz/django-simple-news-app#1]

**Comment by bzzzzzz** [comment]
According to my experience, nobody uses builtin templates, provided with apps, because they never fit the requirements of certain projects. If you think that templates are important, you can provide a pull request for this repository.

**Comment by egorsmkv** [comment]
Согласен, что многие не используют. Их просто используют для примера при написании своих шаблонов.

В свободное время сделаю и отправлю PR.
