### ISSUE TITLE
Add installation section to readme

### ISSUE THREAD

**Issue by egorsmkv** [bzzzzzz/django-simple-news-app#2]

**Comment by bzzzzzz** [comment]
Thank you for this issue, I'll try to provide a new readme ASAP

**Comment by egorsmkv** [comment]
Кстати, такой момент.

Как добавлять Entries? В админ-панели http://imagizer.imageshack.com/img924/2761/BHGO8p.png не наблюдаю кнопки для их создания.

**Comment by bzzzzzz** [comment]
Надо сначала добавить автора, привязанного к текущему пользователю, тогда кнопочка добавления появится. Тоже напишу об этом в ридми.

**Comment by egorsmkv** [comment]
К администратору нужно привязать?

**Comment by bzzzzzz** [comment]
К любому пользователю, который имеет права на добавление записей и планирует их добавлять. Автор - это модель прослойка для пользователя, нужна для отображения дополнительной информации о нем. Новости может создавать только тот пользователь, для которого создан автор
